field update 

 esrally --distribution-version=6.4.0 --track-path=track.json --offline --preserve-install true --car="8gheap"  --on-error=abort


                        {% set docs=10000000 %}
                        {% set bulksize=1000 %}
                        "bulk-size":{{bulksize}},
                        "param-source": "insert-books-subs-parallel",
                        "subs-total":2000,
                        "subs-per-book":10,
                        "books-total": {{docs}}, 
                        {#"not-in use- num docs in subscription":500000#}
                    },
                    "clients": 2
10M docs  50 min by 2 clients got 17 gb storage, 1 g heap. 
2K subscriptions, 50K docs per subscription 


--
runing 4 client on 100M docs almost fully utilizes 16G


2018-10-24 19:51:58,949 ActorAddr-(T|:45633)/PID:3027 esrally.actor ERROR Error in track preparator
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/esrally/utils/modules.py", line 90, in load
    root_module = self._load_component(component_name, module_dirs)

  File "/usr/local/lib/python3.7/site-packages/esrally/utils/modules.py", line 48, in _load_component
    m = importlib.import_module(p)


  File "/home/ec2-user/elasticsearch-index-benchmark/field_update/track_tests.py", line 3, in <module>
    from track import InsertBooksSubsParamSource

ModuleNotFoundError: No module named 'track'

